export const COMMON_HEADER_NAMES: string[] = [
  'Accept',
  'Accept-Charset',
  'Accept-Encoding',
  'Accept-Language',
  'Access-Control-Allow-Origin',
  'Access-Control-Allow-Headers',
  'Access-Control-Allow-Methods',
  'Access-Control-Request-Headers',
  'Access-Control-Request-Method',
  'Authorization',
  'Cache-Control',
  'Connection',
  'Content-Disposition',
  'Content-Encoding',
  'Content-Language',
  'Content-Length',
  'Content-Type',
  'Cookie',
  'DNT',
  'Host',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Unmodified-Since',
  'Origin',
  'Pragma',
  'Proxy-Authorization',
  'Range',
  'Referer',
  'Sec-Fetch-Dest',
  'Sec-Fetch-Mode',
  'Sec-Fetch-Site',
  'Server',
  'Set-Cookie',
  'Strict-Transport-Security',
  'Transfer-Encoding',
  'User-Agent',
  'X-API-Key',
  'X-Auth-Token',
  'X-CSRF-Token',
  'X-Correlation-ID',
  'X-Forwarded-For',
  'X-Forwarded-Host',
  'X-Forwarded-Proto',
  'X-Request-ID',
  'X-Requested-With',
];

export const COMMON_HEADER_VALUES: Record<string, string[]> = {
  'Content-Type': [
    'application/json; charset=utf-8',
    'application/json',
    'application/xml',
    'application/x-www-form-urlencoded',
    'multipart/form-data',
    'text/plain; charset=utf-8',
    'text/html; charset=utf-8',
    'application/octet-stream',
    'application/pdf',
    'image/png',
    'image/jpeg',
  ],
  Accept: [
    'application/json',
    'application/json, text/plain, */*',
    'application/xml',
    'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    '*/*',
  ],
  'Accept-Encoding': ['gzip, deflate, br', 'gzip, deflate', 'identity'],
  'Accept-Language': ['en-US,en;q=0.9', 'en-GB,en;q=0.8', '*'],
  'Cache-Control': ['no-cache', 'no-store, must-revalidate', 'max-age=0', 'max-age=3600', 'public'],
  Connection: ['keep-alive', 'close'],
  Authorization: ['Bearer {{token}}', 'Basic {{credentials}}', 'API-Key {{apiKey}}'],
};
