// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function ClearAllStorage() {
  return window['go']['main']['App']['ClearAllStorage']();
}

export function DeleteStorageItem(arg1) {
  return window['go']['main']['App']['DeleteStorageItem'](arg1);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function GetStorageItem(arg1) {
  return window['go']['main']['App']['GetStorageItem'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SaveStorageItem(arg1, arg2) {
  return window['go']['main']['App']['SaveStorageItem'](arg1, arg2);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
