// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelRequest(arg1:string):Promise<boolean>;

export function ClearAllStorage():Promise<void>;

export function DeleteStorageItem(arg1:string):Promise<void>;

export function ExecuteRequest(arg1:main.ApiRequest):Promise<main.ApiResponse>;

export function GetStorageItem(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveStorageItem(arg1:string,arg2:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
