// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest(arg1) {
  return window['go']['main']['RequestService']['CancelRequest'](arg1);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['RequestService']['ExecuteRequest'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['RequestService']['SetContext'](arg1);
}
