// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function CancelRequest(arg1:string):Promise<boolean>;

export function ExecuteRequest(arg1:main.ApiRequest):Promise<main.ApiResponse>;

export function SetContext(arg1:context.Context):Promise<void>;
